language: c
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "ArduinoJson","NeoPixelBus","SparkFun BME280","DallasTemperature","OneWire","Time"
script:
  - arduino --verify --board esp8266:esp8266:generic:CpuFrequency=80,FlashFreq=40,FlashMode=dio,UploadSpeed=460800,FlashSize=2M,ResetMethod=ck,Debug=Disabled,DebugLevel=None____$PWD/examples/WeatherStation/WeatherStation.ino
notifications:
  email:
    on_success: build@lacool.co
    on_failure: build@lacool.co
